### ISSUE TITLE
single word sentences break the model

### ISSUE THREAD

**Issue by HassanJbara** [BurhanUlTayyab/GPTZero#12]
When playing around with the model I found out that having single word sentences (i.e. single word on its own line) breaks the model. Example:

```
1. **Tailor your resume to the job:** Customize your resume for each job you apply to by highlighting the skills and experience that match the job requirements.
2. **Use keywords:** Use keywords related to the job and industry to help your resume pass through applicant tracking systems (ATS) and catch the eye of hiring managers.

**Content:**
**Style:**

one

2. **Use active language:** Use active language to describe your achievements and responsibilities.

4. **Use a professional tone:** Use a professional tone and avoid using slang, humor, or overly casual language.
```

This text causes the following error:

```bash
Traceback (most recent call last):
  File "C:\Projects\personal\tmp\GPTZero\infer.py", line 29, in <module>
    model(sentence)
  File "C:\Projects\personal\tmp\GPTZero\model.py", line 78, in __call__
    ppl = self.getPPL(line)
          ^^^^^^^^^^^^^^^^^
  File "C:\Projects\personal\tmp\GPTZero\model.py", line 115, in getPPL
    ppl = int(torch.exp(torch.stack(nlls).sum() / end_loc))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot convert float NaN to integer
```
Specifically, `outputs.loss` from the GPT2 model in the line 107 of `model.py` are NaN, which causes this error. I still don't understand why this happens, so maybe you can help me fix this error? 
Assumption: for a single word one shouldn't the logprob of the model for that word alone be returned?

**Comment by Haozhe-Li** [comment]
This is strange, I test single word in my local env it would be `-1` instead of error
